from __future__ import annotations

import argparse
import json
import platform
import sys
import time
from pathlib import Path

from .config import DEFAULT_STACK, StackConfig, load_stack
from .docker import compose_down, compose_ps, compose_up, has_docker
from .health import http_ok, ollama_generate
from .macos import (
    is_apple_silicon,
    is_macos,
    launch_agent_status,
    ollama_bin,
    start_ollama_launch_agent,
    stop_ollama_launch_agent,
)
from .shell import run
from .tuning import TuningResult, apply_autotune, tuning_to_dict


def _load_cfg_with_tuning(stack: str) -> tuple[StackConfig, TuningResult]:
    cfg = load_stack(stack)
    tuning = apply_autotune(cfg)
    return cfg, tuning


def _models_sync(cfg: StackConfig) -> int:
    host = f"{cfg.ollama.host}:{cfg.ollama.port}"
    for model in cfg.ollama.models:
        print(f"pulling {model}...")
        res = run(["ollama", "pull", model], env={"OLLAMA_HOST": host}, check=False)
        if res.code != 0:
            raise RuntimeError(res.stderr or res.stdout or f"failed pulling {model}")
    print("models synced")
    return 0


def _warmup(cfg: StackConfig) -> int:
    if not cfg.ollama.warmup_model:
        print("no warmup_model configured")
        return 0

    ok, msg = ollama_generate(
        f"{cfg.ollama.host}:{cfg.ollama.port}",
        cfg.ollama.warmup_model,
        cfg.ollama.warmup_prompt,
    )
    if not ok:
        raise RuntimeError(f"warmup failed: {msg}")
    print("warmup complete")
    return 0


def _wait_for_ollama(cfg: StackConfig, timeout_s: float = 45.0, interval_s: float = 1.0) -> None:
    url = f"http://{cfg.ollama.host}:{cfg.ollama.port}/api/tags"
    deadline = time.monotonic() + timeout_s
    last_msg = "unknown error"

    while time.monotonic() < deadline:
        ok, msg = http_ok(url, timeout=2.0)
        if ok:
            return
        last_msg = msg
        time.sleep(interval_s)

    raise RuntimeError(
        f"ollama did not become ready within {int(timeout_s)}s at {url}: {last_msg}"
    )


def _write_runtime_env(cfg: StackConfig, tuning: TuningResult) -> None:
    env_path = Path(cfg.root) / ".localai.env"
    host_ram = tuning.specs.mem_gb if tuning and tuning.specs.mem_gb else 32
    lines = [
        "# Generated by localai CLI.",
        f"LOCALAI_HOST_RAM_GB={host_ram}",
    ]
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _cmd_up(args: argparse.Namespace) -> int:
    cfg, tuning = _load_cfg_with_tuning(args.stack)
    _write_runtime_env(cfg, tuning)
    if cfg.ollama.enabled:
        if tuning.enabled and tuning.applied:
            print(f"autotune applied: {json.dumps(tuning.applied)}")
        start_ollama_launch_agent(cfg)
        if args.sync_models or args.warmup:
            _wait_for_ollama(cfg)
        if args.sync_models:
            _models_sync(cfg)
        if args.warmup:
            _warmup(cfg)
    compose_up(cfg)
    print("stack is up")
    return 0


def _cmd_down(args: argparse.Namespace) -> int:
    cfg, _ = _load_cfg_with_tuning(args.stack)
    compose_down(cfg)
    if args.stop_native and cfg.ollama.enabled:
        stop_ollama_launch_agent(cfg)
    print("stack is down")
    return 0


def _cmd_status(args: argparse.Namespace) -> int:
    cfg, tuning = _load_cfg_with_tuning(args.stack)
    status = {
        "platform": platform.platform(),
        "macos": is_macos(),
        "apple_silicon": is_apple_silicon(),
        "autotune": tuning_to_dict(tuning),
        "ollama": {
            "enabled": cfg.ollama.enabled,
            "binary": ollama_bin(),
            "service": launch_agent_status(cfg.ollama.label) if cfg.ollama.enabled and is_macos() else "disabled",
            "endpoint": f"http://{cfg.ollama.host}:{cfg.ollama.port}",
        },
        "docker_compose_ps": compose_ps(cfg) if has_docker() else "docker not found",
    }
    print(json.dumps(status, indent=2))
    return 0


def _cmd_doctor(args: argparse.Namespace) -> int:
    cfg, tuning = _load_cfg_with_tuning(args.stack)
    checks: list[tuple[str, bool, str]] = []

    checks.append(("macOS", is_macos(), platform.system()))
    checks.append(("Apple Silicon", is_apple_silicon(), platform.machine()))
    checks.append(("ollama binary", ollama_bin() is not None, str(ollama_bin())))
    checks.append(("docker binary", has_docker(), "docker" if has_docker() else "missing"))
    checks.append(("autotune enabled", tuning.enabled, json.dumps(tuning.applied or tuning.recommendations)))

    if has_docker():
        d = run(["docker", "info"])
        checks.append(("docker daemon", d.code == 0, d.stderr or "ok"))

    ollama_ok, ollama_msg = http_ok(f"http://{cfg.ollama.host}:{cfg.ollama.port}/api/tags")
    checks.append(("ollama http", ollama_ok, ollama_msg[:120]))

    ui_ok, ui_msg = http_ok(cfg.health.openwebui_url)
    checks.append(("openwebui http", ui_ok, ui_msg[:120]))

    failed = False
    for name, ok, msg in checks:
        icon = "OK" if ok else "FAIL"
        print(f"[{icon}] {name}: {msg}")
        if not ok:
            failed = True
    return 1 if failed else 0


def _cmd_models_sync(args: argparse.Namespace) -> int:
    cfg, _ = _load_cfg_with_tuning(args.stack)
    return _models_sync(cfg)


def _cmd_warmup(args: argparse.Namespace) -> int:
    cfg, _ = _load_cfg_with_tuning(args.stack)
    return _warmup(cfg)


def _cmd_logs(args: argparse.Namespace) -> int:
    cfg, _ = _load_cfg_with_tuning(args.stack)

    if cfg.ollama.enabled:
        log_path = Path.home() / ".localai" / "logs" / "ollama.out.log"
        if log_path.exists():
            out = run(["tail", "-n", str(args.tail), str(log_path)])
            if out.stdout:
                print("# ollama.out.log")
                print(out.stdout)

    cmd = ["docker", "compose"]
    env_file = Path(cfg.root) / ".localai.env"
    if env_file.exists():
        cmd.extend(["--env-file", str(env_file)])
    cmd.extend(["-f", str(cfg.docker.compose_file), "logs", f"--tail={args.tail}"])
    if args.follow:
        cmd.append("-f")
    res = run(cmd, cwd=str(cfg.root))
    if res.stdout:
        print(res.stdout)
    if res.stderr:
        print(res.stderr, file=sys.stderr)
    return res.code


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="localai", description="macOS-first orchestrator for native Ollama + Docker stack")
    p.add_argument("--stack", default=DEFAULT_STACK, help="Path to stack.toml")

    sub = p.add_subparsers(dest="command", required=True)

    sub_up = sub.add_parser("up", help="Start native Ollama and docker services")
    sub_up.add_argument("--sync-models", action="store_true", help="Pull configured models after starting native Ollama")
    sub_up.add_argument("--warmup", action="store_true", help="Run warmup inference after model sync/start")
    sub_up.set_defaults(func=_cmd_up)

    sub_down = sub.add_parser("down", help="Stop docker services")
    sub_down.add_argument("--stop-native", action="store_true", help="Also stop native Ollama launch agent")
    sub_down.set_defaults(func=_cmd_down)

    sub_status = sub.add_parser("status", help="Show stack status")
    sub_status.set_defaults(func=_cmd_status)

    sub_doctor = sub.add_parser("doctor", help="Run system checks")
    sub_doctor.set_defaults(func=_cmd_doctor)

    sub_models = sub.add_parser("models-sync", help="Pull configured Ollama models")
    sub_models.set_defaults(func=_cmd_models_sync)

    sub_warmup = sub.add_parser("warmup", help="Run warmup inference on configured model")
    sub_warmup.set_defaults(func=_cmd_warmup)

    sub_logs = sub.add_parser("logs", help="Show stack logs")
    sub_logs.add_argument("--follow", action="store_true", help="Stream logs")
    sub_logs.add_argument("--tail", type=int, default=100)
    sub_logs.set_defaults(func=_cmd_logs)

    return p


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    try:
        rc = args.func(args)
    except RuntimeError as e:
        print(f"error: {e}", file=sys.stderr)
        raise SystemExit(1) from e

    raise SystemExit(rc)


if __name__ == "__main__":
    main()
